package de.ebrahim.outbox;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/**
 * A message to be published once (and only after) the enclosing database
 * transaction commits.
 *
 * <p>{@code messageId} is generated by the caller and travels with the message
 * as the {@code Nats-Msg-Id} header. Because delivery is at-least-once, the same
 * message id may legitimately reach the broker more than once; JetStream's
 * duplicate window collapses most of those, and consumers must still be
 * idempotent for the rest.
 *
 * <p>Note that {@code payload} is a byte array, so the generated
 * {@code equals}/{@code hashCode} compare it by identity. Compare payloads
 * explicitly if you need value semantics.
 */
public record OutboxMessage(UUID messageId, String subject, Map<String, String> headers, byte[] payload) {

    public OutboxMessage {
        Objects.requireNonNull(messageId, "messageId");
        Objects.requireNonNull(subject, "subject");
        Objects.requireNonNull(payload, "payload");
        if (subject.isBlank()) throw new IllegalArgumentException("subject must not be blank");
        headers = Map.copyOf(Objects.requireNonNull(headers, "headers"));
    }

    public static OutboxMessage of(String subject, byte[] payload) {
        return new OutboxMessage(UUID.randomUUID(), subject, Map.of(), payload);
    }

    public static OutboxMessage of(String subject, String payload) {
        return of(subject, payload.getBytes(StandardCharsets.UTF_8));
    }

    /** Returns a copy with one extra header. Headers are forwarded verbatim to NATS. */
    public OutboxMessage withHeader(String name, String value) {
        Map<String, String> merged = new LinkedHashMap<>(headers);
        merged.put(name, value);
        return new OutboxMessage(messageId, subject, merged, payload);
    }
}
